<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Máster de Bioestadística - Probabilidad y Simulación</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../tema_02/tema_02_2_comparacion_test_y_tamanyos_muestrales_I.html" rel="next">
<link href="../tema_02/tema_02.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script><script src="../site_libs/kePrint-0.0.1/kePrint.js"></script><link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><link rel="stylesheet" href="../css/styles.css">
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../tema_02/tema_02.html">TEMA 2</a></li><li class="breadcrumb-item"><a href="../tema_02/tema_02_1_introduccion.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">1. Conceptos básicos <span style="color:green;">✓</span></span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Introducción</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../DUDAS.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Dudas</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../tema_00/tema_00.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">TEMA 0</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tema_00/tema_00_introduccion.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Introducción</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../tema_01/tema_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">TEMA 1</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tema_01/tema_01_1_introduccion.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1. Introducción <span style="color:green;">✓</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tema_01/tema_01_2_concordancia_categoricas.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">2. Análisis de concordancia en variables categóricas <span style="color:green;">✓</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tema_01/tema_01_3_concordancia_numericas.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">3. Análisis de concordancia en variables numéricas <span style="color:green;">✓</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tema_01/tema_01_4_tamanyo_muestral.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">4. Cálculo del tamaño muestral <span style="color:green;">✓</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../tema_02/tema_02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">TEMA 2</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tema_02/tema_02_1_introduccion.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">1. Conceptos básicos <span style="color:green;">✓</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tema_02/tema_02_2_comparacion_test_y_tamanyos_muestrales_I.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">2. Comparación de test y tratamiento del tamaño muestral (I) <span style="color:green;">✓</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tema_02/tema_02_2_comparacion_test_y_tamanyos_muestrales_II.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">2. Comparación de test y tratamiento del tamaño muestral (II) <span style="color:green;">✓</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tema_02/tema_02_3_curvas_roc.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">3. Validación de biomarcadores. Curvas ROC <span style="color:green;">✓</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tema_02/tema_02_4_tamanyos_muestrales.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">4. Determinación de tamaños muestrales</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../tema_03/tema_03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">TEMA 3</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tema_03/tema_03_1_introduccion.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1. Introducción <span style="color:green;">✓</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tema_03/tema_03_2_selección_aleatoria.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">2. Selección aleatoria de pacientes y asignación de tratamientos <span style="color:red;">✗</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tema_03/tema_03_3_obtener_datos_simulados.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">3. Obtener datos simulados a partir de observaciones reales <span style="color:green;">✓</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tema_03/tema_03_4_remuestreo_inferencia_roc.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">4. Técnicas de remuestreo aplicadas a la inferencia de curvas ROC <span style="color:red;">✗</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="99"><h2 id="toc-title">In this page</h2>
   
  <ul>
<li><a href="#tests-binarios" id="toc-tests-binarios" class="nav-link active" data-scroll-target="#tests-binarios">Tests binarios</a></li>
  <li><a href="#probabilidades-de-clasificaci%C3%B3n" id="toc-probabilidades-de-clasificación" class="nav-link" data-scroll-target="#probabilidades-de-clasificaci%C3%B3n">Probabilidades de clasificación</a></li>
  <li>
<a href="#valores-predictivos" id="toc-valores-predictivos" class="nav-link" data-scroll-target="#valores-predictivos">Valores predictivos</a>
  <ul>
<li><a href="#utilidad" id="toc-utilidad" class="nav-link" data-scroll-target="#utilidad">Utilidad</a></li>
  </ul>
</li>
  <li><a href="#odds" id="toc-odds" class="nav-link" data-scroll-target="#odds">Odds</a></li>
  <li>
<a href="#razones-de-verosimilitud-diagnostic-likelihood-ratio" id="toc-razones-de-verosimilitud-diagnostic-likelihood-ratio" class="nav-link" data-scroll-target="#razones-de-verosimilitud-diagnostic-likelihood-ratio">Razones de verosimilitud (Diagnostic Likelihood Ratio)</a>
  <ul>
<li><a href="#utilidad-1" id="toc-utilidad-1" class="nav-link" data-scroll-target="#utilidad-1">Utilidad</a></li>
  </ul>
</li>
  <li><a href="#diferencias-entre-odds-y-dlr" id="toc-diferencias-entre-odds-y-dlr" class="nav-link" data-scroll-target="#diferencias-entre-odds-y-dlr">Diferencias entre Odds y DLR</a></li>
  <li><a href="#diferencias-entre-valores-predictivos-y-dlr" id="toc-diferencias-entre-valores-predictivos-y-dlr" class="nav-link" data-scroll-target="#diferencias-entre-valores-predictivos-y-dlr">Diferencias entre valores predictivos y DLR</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content column-body" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span class="chapter-title">1. Conceptos básicos <span style="color:green;">✓</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><p><u><strong>Test o prueba diagnóstica</strong></u></p>
<p><strong>Cada prueba diagnóstica tiene por detrás el cómo se he escogido esa muestra.</strong></p>
<p>En general, es cualquier prueba que sirve para determinar la naturaleza de una condición en particular.</p>
<p>En el ámbito médico, es cualquier prueba clínica que se realiza para ayudar en la diagnosis o detección de una enfermedad. Cuando el resultado de una prueba sea X podemos decir que una persona [<strong>puede tener</strong>]{bck_color_02} la enfermedad. (el diagnóstico no lo hace es test)</p>
<p>Introducimos la idea de que una cosa es que el paciente tenga una enfermedad y otra que el test diga que esa persona tiene esa enfermedad.</p>
<p>No confundir con los test a los que suponemos los estadísticos de una hipótesis. (sí, ya, bueno, me parece obvio no confundirlos)</p>
<p><strong>Clasificación</strong> de las pruebas diagnóstica <strong>según el tipo de resultado</strong>:</p>
<ul>
<li>
<strong>Binario</strong>. Dos posibles resultados (padecer o no la enfermedad).</li>
<li>
<strong>Ordinales</strong>. Clasificación del resultado basado en un order. Por ejemplo, la presencia de la enfermedad como: definitivamente, probablemente, probablemente no, definitivamente no.</li>
<li>
<strong>Continuos (biomarcador)</strong>. El resultado del test toma valores en una escala continua, tiene algún tipo de unidad e incluso puede tener un intervalo de valores como resultado.</li>
</ul>
<p>La metodología en los casos que no son binarios adapta la metodología de los casos binarios. <strong>El resultado final es que dada una condición binaria</strong> (pertenece a la categoría ordinal a, tiene un marcador por encima de un punto) <strong>tiene o no la enfermedad</strong>.</p>
<p><strong>Clasificación</strong> de las pruebas diagnóstica <strong>según la forma de elegir los individuos</strong>:</p>
<ul>
<li>
<strong>Estudios de cohorte</strong>. Dada una muestra de la población objetivo se les aplica la prueba diagnóstica. También se recoge la información sobre el estado real de la enfermedad en estos sujetos utilizando una prueba de referencia (gold standard).
<ul>
<li>
<strong>Cohorte retrospectiva</strong>. Sabiendo que están expuesto al riesgo pero aun no han desarrollado la enfermedad.</li>
</ul>
</li>
<li>
<strong>Estudios caso-control</strong>. Dada una muestra de sujetos enfermos / con la característica (casos) y otra muestra de no enfermos / sin la característica (controles) se aplica la prueba diagnóstica a los sujtos de ambas muestras.</li>
</ul>
<p>En casos donde dadas n prueba diagnóstica, ver qué tipo de destudios hacemos para poder compararlas: <strong>comparativa del diseño</strong>.</p>
<p>Comparativa entre dos pruebas o contra la gold standar. ¿Y si tenemos tres prueba diagnóstica? ¿Hacemos comparativas dos a dos?</p>
<section id="tests-binarios" class="level2"><h2 class="anchored" data-anchor-id="tests-binarios">Tests binarios</h2>
<p>Dada una gold standar, sea <span class="math inline">\(D\)</span> v.a. dicotómica que denota el estado de la enfermedad: variable que dice el estado real del paciente respecto a la enfermedad.</p>
<p><span class="math display">\[
D =
\begin{cases}
1, &amp; \text{si el sujeto tiene la enfermedad} \\
0, &amp; \text{si el sujeto no tiene la enfermedad} \\
\end{cases}
\]</span></p>
<p><span class="math display">\[\rho = \text{prevalencia} = P(D=1) = \text{probabilidad real de tener la enfermedad.}\]</span></p>
<p>Sea <span class="math inline">\(Y\)</span> v.a.que modeliza el resultado de la prueba diagnóstica: variable que dice el resiltado de la prueba diagnóstica.</p>
<p><span class="math display">\[
Y =
\begin{cases}
1, &amp; \text{si el resultado del test diagnóstico es positivo} \\
0, &amp; \text{si el resultado del test diagnóstico es negativo} \\
\end{cases}
\]</span></p>
<p><u><strong>Clasificación</strong></u></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: center; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px; font-weight: bold; color: white !important; padding-right: 4px; padding-left: 4px; background-color: #004080 !important;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Verdadero estado de la enfermedad
</div></th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th" style="text-align: center; background-color: #004080 !important;">Resultado del test</th>
<th data-quarto-table-cell-role="th" style="text-align: center; background-color: #004080 !important;">D = 1</th>
<th data-quarto-table-cell-role="th" style="text-align: center; background-color: #004080 !important;">D = 0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center; background-color: #004080 !important; font-weight: bold; color: white !important;">Y = 1</td>
<td style="text-align: center; background-color: #004080 !important; background-color: lightgreen !important;">Verdadero positivo</td>
<td style="text-align: center; background-color: #004080 !important; background-color: lightcoral !important;">Falso positivo</td>
</tr>
<tr class="even">
<td style="text-align: center; background-color: #004080 !important; font-weight: bold; color: white !important;">Y = 0</td>
<td style="text-align: center; background-color: #004080 !important; background-color: lightcoral !important;">Falso negativo</td>
<td style="text-align: center; background-color: #004080 !important; background-color: lightgreen !important;">Verdadero negativo</td>
</tr>
</tbody>
<tfoot><tr class="even">
<td style="text-align: center; padding: 0; border: 0;">
<sup></sup> Y, D ∈ {0,1}</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr></tfoot>
</table>
</div>
</div>
<p>El test da el resultado para la enfermedad, no el diagnóstoco. Queremos medir si la prueba diagnóstica es válida para que, cuando esta de positivo o negativo, una persona 100tífika pueda tomar una decisión en base a esa prueba.</p>
<div class="recuadro_1">
<p><u><strong>Medidas asociadas a un test.</strong></u></p>
<p><strong>Probabilidades de clasificación (correcta a un individuo).</strong><br>
- Se<br>
- 1-Sp</p>
<p><strong>Probabilidad de emitir un diagnóstico erróneo (contexto no médico).</strong></p>
<p><strong>Valores predictivos.</strong></p>
<p><strong>Razón de verosimilitudes.</strong><br>
- Odds pre-test<br>
- Odds post test</p>
</div>
</section><section id="probabilidades-de-clasificación" class="level2"><h2 class="anchored" data-anchor-id="probabilidades-de-clasificación">Probabilidades de clasificación</h2>
<p><strong>A partir de las probabilidades de estos sucesos se definen las siguientes probabilidades.</strong></p>
<ul>
<li>
<strong>Probabilidades de acierto</strong>. Probabilidades que determinan cómo de válidas son las pruebas que estamos midiendo</li>
<li>
<strong>Probabilidades de fallo</strong>. Consecuencia de haber creado las probabilidades de acierto.</li>
</ul>
<div class="recuadro_1">
<p><u><strong>Probabilidades de acierto.</strong></u></p>
<p>Probabilidades que determinan cómo de válidas son las pruebas que estamos midiendo: la sensibilidad (<strong>Se</strong>) y la especificidad (<strong>Sp</strong>). Ambas son probabilides de acertar.</p>
<p><strong>Sensibilidad. Probabilidad de clasificar correctamente a un enfermo.</strong> (“enfermo” y no “positivo” porque se que la realidad es enfermo - por ejemplo, gracias a la gold standar )</p>
<p><span class="math display">\[Se = p(Y = 1 | D = 1)\]</span></p>
<p><strong>Especificidad. Probabilidad de clasificar correctamente a un sano.</strong></p>
<p><span class="math display">\[Sp = p(Y = 0 | D = 0)\]</span></p>
</div>
<div class="recuadro_1">
<p><u><strong>Probabilidades de fallo.</strong></u></p>
<p>También están relacionadas con las probabilidades de fallo ya que creamos las probabiliades de error falso positivo (<strong>FP</strong>) y falso negativo (<strong>FN</strong>).</p>
<p><strong>Probabilidad de falsos negativos.</strong> Probabilidad de clasificar erróneamente a un enfermo.</p>
<p><span class="math display">\[p(FN) = 1 - Se = 1 - p(Y = 1 | D = 1) = p(Y = 0 | D = 1)\]</span></p>
<p><strong>Probabilidad de falsos positivos.</strong> Probabilidad de clasificar erróneamente a un sano.</p>
<p><span class="math display">\[p(FN) = 1 - Sp = 1 - p(Y = 0 | D = 0) = p(Y = 1 | D = 0)\]</span></p>
</div>
<div class="recuadro_1">
<p><u><strong>Probabilidades de clasificar como positivo.</strong></u></p>
<p><strong>Sensibilidad.</strong> <span class="math inline">\(Se = p(Y = 1 | D = 1)\)</span></p>
<p><strong>1 - especificidad.</strong> <span class="math inline">\(1 - Sp = 1 - p(Y = 0 | D = 0) = p(Y = 1 | D = 0)\)</span></p>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: center; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px; font-weight: bold; color: white !important; padding-right: 4px; padding-left: 4px; background-color: #004080 !important;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Verdadero estado de la enfermedad
</div></th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th" style="text-align: center; background-color: #004080 !important;">Resultado del test</th>
<th data-quarto-table-cell-role="th" style="text-align: center; background-color: #004080 !important;">D = 1</th>
<th data-quarto-table-cell-role="th" style="text-align: center; background-color: #004080 !important;">D = 0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center; background-color: #004080 !important; font-weight: bold; color: white !important;">Y = 1</td>
<td style="text-align: center; background-color: #004080 !important; background-color: lightgreen !important;">TP = Se</td>
<td style="text-align: center; background-color: #004080 !important; background-color: lightcoral !important;">FP = 1- Se</td>
</tr>
<tr class="even">
<td style="text-align: center; background-color: #004080 !important; font-weight: bold; color: white !important;">Y = 0</td>
<td style="text-align: center; background-color: #004080 !important; background-color: lightcoral !important;">FN = 1 - Sp</td>
<td style="text-align: center; background-color: #004080 !important; background-color: lightgreen !important;">TN = Sp</td>
</tr>
</tbody>
<tfoot><tr class="even">
<td style="text-align: center; padding: 0; border: 0;">
<sup></sup> Y, D ∈ {0,1}</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr></tfoot>
</table>
</div>
</div>
<p><span class="bck_color_04">Qué paxa para ser un test ideal.</span> <span class="math inline">\(\rightarrow\)</span> Las probabilidades de acertar son máximas <span class="math inline">\(\rightarrow\)</span> <span class="bck_color_04">Se = Sp = 1.</span><br><span class="bck_color_03">Qué paxa para ser un test inutil.</span> <span class="math inline">\(\rightarrow\)</span> La probabilidad de que el test de positivo es la misma cuando el sujeto está enfermo que cuando está sano. <span class="math inline">\(\rightarrow\)</span> <span class="bck_color_03">Se = 1 – Sp.</span></p>
<p><span class="bck_color_03">Qué más paxa para ser un test inútil.</span></p>
<ul>
<li>
<span class="bck_color_03">Dar positivo a todo el mundo.</span> <span class="math inline">\(\rightarrow\)</span> Dar positivo tenga o no la enfermedad.
<ul>
<li>Maximiza el acierto <span class="math inline">\(Se\)</span> (todos los positivos están identificados).</li>
<li>pero maximiza también el error <span class="math inline">\(1-Sp\)</span> (todos los negativos se asigna como positivos).</li>
</ul>
</li>
<li>
<span class="bck_color_03">Dar negativo a todo el mundo.</span> <span class="math inline">\(\rightarrow\)</span> Dar negativo esté sano o no.
<ul>
<li>Maximiza el acierto <span class="math inline">\(Sp\)</span> (todos los negativos están identificados).</li>
<li>pero maximiza también el error <span class="math inline">\(1-Se\)</span> (todos los positivos se asigna como negativos).</li>
</ul>
</li>
</ul>
<p><strong>Si quiero hacer una compartaiva con varias pruebas diagnósticas, ¿qué métrica priorizo para la comprativa?</strong> (novio guapo y pobre vs novio feo y rico)</p>
<p><strong>Necesitamos una escala doble</strong>. Así podemos pasar nuestra decision en una comparativa donde las dos comparativas iniciales están reducidas a una única dimensión.</p>
<p><span class="math display">\[
\begin{aligned}
p(\text{"emitir un resultado erróneo"}) &amp;= p(Y \neq D) \\
&amp;= p(FP) + p(FN) \\
&amp;= p(Y=1 \cap D=0) + p(Y=0 \cap D=1) \\
&amp;= p(Y=1 | D=0) \cdot p(D=0) + p(Y=0 | D=1) \cdot p(D=1) \\
&amp;= (\text{un error}) \cdot p(D=0) + p(\text{otro error}) \cdot \rho \\
&amp;= (1 - \text{Sp}) \cdot (1-\rho) + (1 - \text{Se}) \cdot \rho
\end{aligned}
\]</span><br>
::: recuadro_1 <strong>Cuál de los dos errores tiene más “importancia”.</strong></p>
<ul>
<li>Si <span class="math inline">\(\rho &gt; 0.5 \Rightarrow\)</span> más peso <span class="math inline">\(1-Se \Rightarrow\)</span> más peso los FN.</li>
<li>Si <span class="math inline">\(\rho &lt; 0.5 \Rightarrow\)</span> más peso <span class="math inline">\(1-Sp \Rightarrow\)</span> más peso los FP. :::</li>
</ul>
<p><u><strong>Ejemplo.</strong></u></p>
<p>Imaginemos una una prueba diagnóstica que siempre da positivo a cualquier individuo.</p>
<p><span class="math inline">\(p(Y=1 | D=0) = p(Y=1 | D=1) = 1.\)</span></p>
<ul>
<li><p>Si la prevalencia es grande la prueba es fantástica.</p></li>
<li><p>Si la prevalencia es pequeña la prueba apesta.</p></li>
<li><p>La prueba no me sirve para nada porque no discrimina.</p></li>
</ul>
<p>Cuando comparamos entre varias prueba diagnóstica tenemos dos medidas que evalúan la calidad de cada una de las pruebas. Para lidiar ese problema usamos otra medida mediante los valores predictivos y las razones de verosimilitudes.</p>
</section><section id="valores-predictivos" class="level2"><h2 class="anchored" data-anchor-id="valores-predictivos">Valores predictivos</h2>
<p><strong><em>Vale, mijo, pero cuando yo hago un test y tengo un positivo, ¿qué hago?</em></strong></p>
<p>Desde un punto de vista clínico, la utilidad de una test recae en tener el resultado de la prueba y hacer un diagnóstico.</p>
<p>La utilidad de una prueba diagnóstica puede cuantificarse analizando <strong>las posibilidades o PROBABILIDADES de que el resultado de la prueba diagnóstica sea capaz de predecir el verdadero estado del sujeto</strong>.</p>
<div class="recuadro_1">
<p><strong>Valor predictivo positivo</strong>: <span class="math inline">\(PPV = P(D=1 | Y=1)\)</span><br><strong>Valor predictivo negativo</strong>: <span class="math inline">\(NPV = P(D=0 | Y=0)\)</span></p>
<p>Es decir:</p>
<ul>
<li><strong>Si da un resultado positivo, ¿cuál es la probabilidad de que realmente esté enfermo?</strong></li>
<li><strong>Si da un resultado negativo, ¿cuál es la probabilidad de que realmente esté sano?</strong></li>
</ul>
<p>Test ideal: PPV = NPV = 1</p>
<p>Test sin utilidad: PPV = <span class="math inline">\(\rho\)</span> y NPV = 1 - <span class="math inline">\(\rho\)</span></p>
<p><strong>Los valores predictivos dependen de la prevalencia.</strong></p>
<p><strong>Que un test sea más sensible o más específico no depende de la prevalencia.</strong></p>
</div>
<p><u><strong>Ejemplo 2.1.</strong></u></p>
<p>Se considera una prueba para diagnosticar el cáncer de mama. Supongamos que la prevalencia en la población femenina es del 1%. En un estudio caso-control las probabilidades de resultados positivos del test fueron 0,85 dentro de los casos y 0,03 dentro de los controles. ¿Cuáles son los valores predictivos positivo y negativo?</p>
<p>Que sea de caso-control ahora me vale verga no me sirve para nada en este punto de evaluacion del modelo.</p>
<p><span class="math inline">\(0.01 = p(D=1) = \text{prevalencia}\)</span><br><span class="math inline">\(0.85 = p(Y=1 | D=1) = Se\)</span><br><span class="math inline">\(0.03 = p(Y=1 | D=0) = 1-Sp\)</span></p>
<p><u>Cálculo del PPV.</u></p>
<p><span class="math display">\[\begin{aligned} PPV &amp;= P(D=1 | Y=1) \\ &amp;= \frac{p(D=1 \cap Y=1)}{p(Y=1)} \\ &amp;= \frac{p(Y=1 | D=1) · p(D=1)} {p(Y=1 | D=1) · p(D=1) + p(Y=1 | D=0) · p(D=0)} \\ &amp;= \frac{0.85 · 0.01}{0.85 · 0.01 + 0.03 · 0.99} \end{aligned}\]</span></p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="op">(</span><span class="op">(</span><span class="fl">0.85</span> <span class="op">*</span> <span class="fl">0.01</span><span class="op">)</span> <span class="op">/</span> <span class="op">(</span><span class="fl">0.85</span> <span class="op">*</span> <span class="fl">0.01</span> <span class="op">+</span> <span class="fl">0.03</span> <span class="op">*</span> <span class="fl">0.99</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2225131</code></pre>
</div>
</div>
<p>El 22.25 % de los resultados positivos padecerán la enfermedad.</p>
<p><u>Cálculo del NPV.</u></p>
<p><span class="math display">\[\begin{aligned} NPV &amp;= P(D=0 | Y=0) \\ &amp;= \frac{p(D=0 \cap Y=0)}{p(Y=0)} \\ &amp;= \frac{p(Y=0 | D=0) · p(D=0)} {p(Y=0 | D=0) · p(D=0) + p(Y=0 | D=1) · p(D=1)} \\ &amp;= \frac{(1-0.03) · (1-0.99)}{(1-0.03) · (1-0.99) + (1-0.85) · 0.99} \end{aligned}\]</span></p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="op">(</span><span class="op">(</span><span class="fl">1</span><span class="op">-</span><span class="fl">0.03</span><span class="op">)</span> <span class="op">*</span> <span class="fl">0.99</span><span class="op">)</span><span class="op">/</span><span class="op">(</span><span class="op">(</span><span class="fl">1</span><span class="op">-</span><span class="fl">0.03</span><span class="op">)</span> <span class="op">*</span> <span class="op">(</span><span class="fl">1</span><span class="op">-</span><span class="fl">0.01</span><span class="op">)</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span><span class="op">-</span><span class="fl">0.85</span><span class="op">)</span> <span class="op">*</span> <span class="fl">0.01</span><span class="op">)</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9984404</code></pre>
</div>
</div>
<p>El 99.84 % de los resultados negativos no padecerán la enfermedad.</p>
<p>La prueba diagnóstica perfecta no es. Si fuera perfecta tendríamos que haber obtenido un 1 en ambos valores predictivos (que dependen de los resultados de la prueba). Ya que eso significaría:</p>
<ul>
<li>PPV=1: que cuando la prueba da positivo la probabilidad de que el individuo sea un positivo es 1 AKA todos los positivos son TP.<br>
</li>
<li>NPV=1: que cuando la prueba da negativo la probabilidad de que el individuo sea un negativo es 1 AKA todos los negativos son TN.</li>
</ul>
<section id="utilidad" class="level3"><h3 class="anchored" data-anchor-id="utilidad">Utilidad</h3>
<p>¿Podemos hacer una criba?</p>
<p>Para una persona que da un resultado negativo tenemos una probabilidad muy alta de no tener la enfermedad (0.9984). <strong>Es importante asegurarse de que si a una paciente se le dice que está sano realmente lo esté.</strong></p>
<p>La prueba no sirve para diagnosticar un positivo de la muestra. Para los individuos donde la prueba dé positivo o repito la prueba o hago otro test diferente.</p>
<p>¿Qué miramos en esta prueba o qué utilidad le damos? Aquello que nos conviene: los resultados o las probabilidades altas.</p>
<table class="table">
<colgroup>
<col style="width: 6%">
<col style="width: 36%">
<col style="width: 56%">
</colgroup>
<thead><tr class="header">
<th><strong>Métrica</strong></th>
<th><strong>Interpretación</strong></th>
<th><strong>Ejemplo</strong></th>
</tr></thead>
<tbody>
<tr class="odd">
<td><strong>VPP &gt; 90%</strong></td>
<td>La prueba tiene un excelente valor predictivo positivo, indicando alta probabilidad de enfermedad en positivos.</td>
<td>“Con un VPP de 95%, podemos decir que 95 de cada 100 pacientes con un resultado positivo en esta prueba realmente tienen la enfermedad, lo que la hace altamente confiable para confirmar el diagnóstico.”</td>
</tr>
<tr class="even">
<td><strong>VPP entre 70%-90%</strong></td>
<td>La prueba tiene un buen valor predictivo positivo, útil para confirmar la enfermedad.</td>
<td>“Un VPP de 80% significa que 8 de cada 10 pacientes con resultado positivo tienen la enfermedad, lo que hace que esta prueba sea útil, pero no definitiva.”</td>
</tr>
<tr class="odd">
<td><strong>VPP entre 50%-70%</strong></td>
<td>La prueba tiene una utilidad moderada, pero debe usarse con precaución para confirmar la enfermedad.</td>
<td>“Con un VPP de 60%, aunque la prueba identifica correctamente a la mayoría de los positivos, hay un riesgo significativo de falsos positivos, lo que podría llevar a sobretratamientos.”</td>
</tr>
<tr class="even">
<td><strong>VPP &lt; 50%</strong></td>
<td>La prueba tiene un bajo valor predictivo positivo y es poco fiable para confirmar la enfermedad.</td>
<td>“Un VPP de 40% indica que menos de la mitad de los pacientes con un resultado positivo realmente tienen la enfermedad, lo que limita su utilidad diagnóstica.”</td>
</tr>
<tr class="odd">
<td><strong>VPN &gt; 90%</strong></td>
<td>La prueba tiene un excelente valor predictivo negativo, útil para descartar la enfermedad.</td>
<td>“Con un VPN de 98%, podemos afirmar que 98 de cada 100 pacientes con un resultado negativo realmente no tienen la enfermedad, lo que garantiza confianza en descartar el diagnóstico.”</td>
</tr>
<tr class="even">
<td><strong>VPN entre 70%-90%</strong></td>
<td>La prueba tiene un buen valor predictivo negativo, adecuada para descartar la enfermedad.</td>
<td>“Un VPN de 85% implica que, aunque no perfecto, la mayoría de los pacientes con resultados negativos están libres de enfermedad, lo que da tranquilidad en el diagnóstico.”</td>
</tr>
<tr class="odd">
<td><strong>VPN entre 50%-70%</strong></td>
<td>La prueba tiene utilidad limitada para descartar la enfermedad.</td>
<td>“Con un VPN de 65%, la prueba reduce la probabilidad de enfermedad en negativos, pero no lo suficiente como para descartar por completo el diagnóstico.”</td>
</tr>
<tr class="even">
<td><strong>VPN &lt; 50%</strong></td>
<td>La prueba tiene un bajo valor predictivo negativo y es poco fiable para descartar la enfermedad.</td>
<td>“Un VPN de 45% significa que menos de la mitad de los resultados negativos están libres de enfermedad, lo que genera dudas sobre su utilidad para descartar casos.”</td>
</tr>
</tbody>
</table></section></section><section id="odds" class="level2"><h2 class="anchored" data-anchor-id="odds">Odds</h2>
<p><strong>Dependen de la prevalencia.</strong></p>
<p>Representan la razón entre la probabilidad de que ocurra un evento y la probabilidad de que no ocurra.</p>
<p><span class="math display">\[Odds = \frac{p(D=1)}{1-p(D=1)}\]</span></p>
<p>Se interpretan como _<strong>por cada vez que ocurre el evento, hay x veces en las que el evento no ocurre_</strong>.</p>
</section><section id="razones-de-verosimilitud-diagnostic-likelihood-ratio" class="level2"><h2 class="anchored" data-anchor-id="razones-de-verosimilitud-diagnostic-likelihood-ratio">Razones de verosimilitud (Diagnostic Likelihood Ratio)</h2>
<p><strong>No dependen de la prevalencia</strong>: son medidas inherentes a la prueba diagnóstica.</p>
<p>Utilizadas en el contexto de pruebas diagnósticas <strong>para medir la capacidad de una prueba para diferenciar entre personas con y sin enfermedad</strong>.</p>
<p><strong>Indican la verosimilitud de</strong> o cómo de creíble/plausible/admisible son <strong>los resultados positvos y los resultados negativos</strong>.</p>
<p><span class="math inline">\(DLR^{???} = \frac{P(Y=??? | D=111)}{P(Y=??? | D=000)}, \quad DLR^{???} \in (0, \infty)\)</span></p>
<div class="recuadro_1">
<p><strong>Razón de verosimilitud de diagnóstico positivo:</strong> se trata de una comparación de dos situaciones donde tengo resultados positivos. <span class="math inline">\(DLR^+ = \frac{P(Y=1 | D=1)}{P(Y=1 | D=0)} = \frac{Se}{1 - Sp}, \quad DLR^+ \in (0, \infty)\)</span></p>
<p><strong>Cuánto más probable es obtener un resultado positivo en alguien con la enfermedad comparado con alguien sin la enfermedad.</strong></p>
</div>
<p>Comparo cómo de creible es tener un positivo en los sanos respecto a tener un positivo en los enfermos. Lo idóneo es tener unas razones de verosimiltud positivas altas, ya que refleja que hay mucha más probabilidad de tener positivos en los enfermos que de tener positivos en los sanos.</p>
<div class="recuadro_1">
<p><strong>Razón de verosimilitud de diagnóstico negativo:</strong> se trata de una comparación de dos situaciones donde tengo resultados negativos. <span class="math inline">\(DLR^- = \frac{P(Y=0 | D=1)}{P(Y=0 | D=0)} = \frac{1 - Se}{Sp}, \quad DLR^- \in (0, \infty)\)</span></p>
<p><strong>Cuánto más probable es obtener un resultado negativo en alguien con la enfermedad comparado con alguien sin la enfermedad.</strong></p>
</div>
<p>Comparo cómo de creible es tener un negativo en los sanos respecto a tener un negativo en los enfermos. Lo idóneo es tener unas razones de verosimiltud negativas bajas, ya que refleja que hay mucha menos probabilidad de tener negativo en los enfermos que de tener negativo en los sanos.</p>
<p><span class="bck_color_02"><strong>Test ideal:</strong></span></p>
<ul>
<li>Pensemos:
<ul>
<li>Quiero que la probabilidad de <span class="math inline">\(P(Y=1 | D=1)\)</span> sea mayor a <span class="math inline">\(P(Y=1 | D=0) \Rightarrow P(Y=1 | D=1) &gt;&gt;&gt; P(Y=0 | D=1) \Rightarrow\)</span> <span class="bck_color_02"><span class="math inline">\(DLR^+ = +\infty\)</span></span><br>
</li>
<li>Quiero que la probabilidad de <span class="math inline">\(P(Y=0 | D=1)\)</span> sea menor a <span class="math inline">\(P(Y=0 | D=0) \Rightarrow P(Y=0 | D=1) &lt;&lt;&lt; P(Y=0 | D=0) \Rightarrow\)</span> <span class="bck_color_02"><span class="math inline">\(DLR^- = 0\)</span></span>
</li>
</ul>
</li>
<li>Si no llegamos a ese punto, <span class="bck_color_02"><strong>al menos</strong></span>:
<ul>
<li>
<span class="bck_color_02"><span class="math inline">\(DLR^+ \ge 1\)</span></span><br>
</li>
<li><span class="bck_color_02"><span class="math inline">\(DLR^- \le 1\)</span></span></li>
</ul>
</li>
</ul>
<p><span class="bck_color_02"><strong>Test no informativo:</strong></span></p>
<ul>
<li>El test tiene la misma probabilidad de un resultado positivo en el grupo de los enfermos que en el grupo de los sanos.<br>
</li>
<li>El test tiene la misma probabilidad de un resultado negativo en el grupo de los sanos que en el grupo de los enfermos.</li>
<li>Ambos puntos se resumen en que un test no informativo es aquel que: <span class="math inline">\(DLR^+ = DLR^- = 1\)</span>
</li>
</ul>
<p><span class="bck_color_02"><strong>Test que no quiero:</strong></span></p>
<ul>
<li>El test no tiene mayor probabilidad de resultado positivo en el grupo de los enfermos que en el grupo de los sanos. <span class="math inline">\(\Rightarrow DLR^+ \lt 1\)</span>.<br>
</li>
<li>El test no tiene mayor probabilidad de resultado negativo en el grupo de los sanos que en el grupo de los enfermos. <span class="math inline">\(\Rightarrow DLR^- \gt 1\)</span>.</li>
</ul>
<p>Las razones de verosimilitud cuantifican el <strong>conocimiento que se ha ganado</strong> acerca de la presencia de la enfermedad <strong>tras realizar el test</strong> AKA <strong>sirven para evaluar la utilidad de una prueba diagnóstica.</strong></p>
<p>Pasamos de comparar <em>probabilidad de tener la enfermedad vs probabilidad de no tenerla</em> a comparar <em>probabilidad de tener la enfermedad sabiendo el resultados del test vs.&nbsp;probabilidad de no tener la enfermedad sabiendo el resultado del test</em>.</p>
<p><span class="math display">\[
\displaylines{
\text{probabilidad de tener la enfermedad} \\
\text{vs.} \\
\text{probabilidad de no tenerla} \\
{\Downarrow} \\
\text{probabilidad de tener la enfermedad sabiendo el resultados del test} \\
\text{vs.} \\
\text{probabilidad de no tenerla sabiendo el resultados del test}  \\
}
\]</span></p>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead><tr class="header">
<th><strong>Interpretación</strong></th>
<th><strong>Valor deseado</strong></th>
<th><strong>Valores útiles</strong></th>
</tr></thead>
<tbody>
<tr class="odd">
<td>DLR+ &gt; 1: un resultado positivo aumenta la probabilidad de enfermedad.</td>
<td>Cuanto más alto es el DLR+, mayor es la utilidad de la prueba para confirmar la enfermedad.</td>
<td>Valores típicamente considerados útiles: DLR+ &gt; 10.</td>
</tr>
<tr class="even">
<td>DLR− &lt; 1: Un resultado negativo disminuye la probabilidad de enfermedad.</td>
<td>Cuanto más cerca de 0 es el DLR−, mayor es la utilidad de la prueba para descartar la enfermedad.</td>
<td>Valores típicamente considerados útiles: DLR− &lt; 0.1.</td>
</tr>
</tbody>
</table>
<table class="table">
<colgroup>
<col style="width: 10%">
<col style="width: 44%">
<col style="width: 44%">
</colgroup>
<thead><tr class="header">
<th><strong>Valor del DLR</strong></th>
<th><strong>Interpretación</strong></th>
<th><strong>Ejemplo</strong></th>
</tr></thead>
<tbody>
<tr class="odd">
<td><strong>DLR+ &gt; 10</strong></td>
<td>Prueba diagnóstica muy útil para confirmar la enfermedad.</td>
<td>“Con un DLR+ de 12, esta prueba tiene un alto valor confirmatorio, ya que los pacientes positivos tienen 12 veces más probabilidades de tener la enfermedad que los negativos.”</td>
</tr>
<tr class="even">
<td><strong>DLR+ entre 5 y 10</strong></td>
<td>Moderada utilidad para confirmar la enfermedad.</td>
<td>“Un DLR+ de 6 indica que la prueba tiene utilidad razonable para confirmar la enfermedad, pero no es definitiva.”</td>
</tr>
<tr class="odd">
<td><strong>DLR+ entre 2 y 5</strong></td>
<td>Baja utilidad para confirmar la enfermedad.</td>
<td>“Con un DLR+ de 3, la prueba incrementa la probabilidad de enfermedad, pero su utilidad diagnóstica es limitada.”</td>
</tr>
<tr class="even">
<td><strong>DLR+ &lt; 2</strong></td>
<td>Escasa o nula utilidad para confirmar la enfermedad.</td>
<td>“Un DLR+ de 1.5 sugiere que esta prueba no es útil para confirmar la enfermedad en la práctica clínica.”</td>
</tr>
<tr class="odd">
<td><strong>DLR- &lt; 0.1</strong></td>
<td>Prueba diagnóstica muy útil para descartar la enfermedad.</td>
<td>“Con un DLR- de 0.05, esta prueba tiene un excelente valor para descartar la enfermedad, reduciendo la probabilidad casi a cero.”</td>
</tr>
<tr class="even">
<td><strong>DLR- entre 0.1 y 0.2</strong></td>
<td>Moderada utilidad para descartar la enfermedad.</td>
<td>“Un DLR- de 0.15 indica que la prueba es razonablemente útil para descartar la enfermedad, pero no es concluyente.”</td>
</tr>
<tr class="odd">
<td><strong>DLR- entre 0.2 y 0.5</strong></td>
<td>Baja utilidad para descartar la enfermedad.</td>
<td>“Con un DLR- de 0.3, la prueba reduce la probabilidad de enfermedad, pero su capacidad para descartarla es limitada.”</td>
</tr>
<tr class="even">
<td><strong>DLR- &gt; 0.5</strong></td>
<td>Escasa o nula utilidad para descartar la enfermedad.</td>
<td>“Un DLR- de 0.6 sugiere que esta prueba no es adecuada para descartar la enfermedad en la práctica clínica.”</td>
</tr>
</tbody>
</table>
<section id="utilidad-1" class="level3"><h3 class="anchored" data-anchor-id="utilidad-1">Utilidad</h3>
<p><strong>Ver cuánta información añade el resultado de una prueba diagnóstica.</strong></p>
<p>Tras realizar el test, cómo cambia el resultado esa percepción sobre la presencia de la enfermedad.</p>
<p><span class="math display">\[\textbf{En ausencia de test} \Rightarrow \quad \text{Odd pre-test} = \frac{p(D=1)}{p(D=0)}\]</span></p>
<p><span class="math display">\[\textbf{Después de realizar el test} \Rightarrow \quad \text{Odd post-test} = \frac{p(D=1 | Y)}{p(D=0 | Y)}\]</span></p>
<p><span class="math display">\[\text{Odd post-test} = \text{Odd pre-test} × DLR\]</span> - El DLR cuantifican el cambio en las odds de la enfermedad por el conocimiento del resultado del test.<br>
- A estas razones de verosimilitud de diagnóstico también se les conoce como factores Bayes.</p>
<p><span class="math display">\[\text{Odd post-test (con Y=1)} = \text{Odd pre-test} × DLR^+\]</span></p>
<p><span class="math display">\[\text{Odd post-test (con Y=0)} = \text{Odd pre-test} × DLR^-\]</span></p>
<p><strong>La forma de interpretar las razones de verosimilitud no es probabilistas.</strong></p>
</section></section><section id="diferencias-entre-odds-y-dlr" class="level2"><h2 class="anchored" data-anchor-id="diferencias-entre-odds-y-dlr">Diferencias entre Odds y DLR</h2>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead><tr class="header">
<th><strong>Aspecto</strong></th>
<th><strong>Odds</strong></th>
<th><strong>Razones de verosimilitud</strong></th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Definición</td>
<td>Razón entre probabilidad de éxito y fracaso.</td>
<td>Relación de la probabilidad de tener resultados positivos/negativos en cada uno de los grupos.</td>
</tr>
<tr class="even">
<td>Aplicación</td>
<td>Describe la probabilidad relativa de un evento.</td>
<td>Evalúa la capacidad de una prueba diagnóstica para discriminar entre personas con y sin enfermedad.</td>
</tr>
<tr class="odd">
<td>Unidades</td>
<td>Número puro.</td>
<td>Número puro.</td>
</tr>
<tr class="even">
<td>Relación con pruebas diagnósticas</td>
<td>Se usa en la conversión entre probabilidad y razones de verosimilitud.</td>
<td>Se usa para ajustar la probabilidad pre-prueba y calcular la probabilidad post-prueba.</td>
</tr>
</tbody>
</table>
<p><u><strong>Ejemplo 2.1. (cont.)</strong></u></p>
<p><span class="math inline">\(DLR^+ = \frac{Se}{1-Sp} = \frac{0.85}{1-0.97} = 28.3333\)</span><br><span class="math inline">\(DLR^- = \frac{1-Se}{Sp} = \frac{1-0.85}{0.97} = 0.1546\)</span></p>
<p>[Estas razones de verosimilitud indican que la prueba tiene una buena capacidad para confirmar la enfermedad (<span class="math inline">\(DLR^+ &gt; 10\)</span>) y una moderada capacidad para descartarla (<span class="math inline">\(DLR^- &lt;0.2\)</span>).]{bck_color_02}</p>
<p>La estimacion para las razones dependen de las estimaciones de Se y Sp. Los valores predictivos no.</p>
<p><span class="math display">\[\text{Odd pre-test} = \frac{p(D=1)}{p(D=0)} = \frac{0.01}{1-0.01} = 0.0101\]</span> <strong>Antes de hacerme la prueba la única informacion que tengo la prevalencia de la enfermedad.</strong></p>
<p><span class="math display">\[\text{Odd post-test (para un resultado positivo)} = \frac{p(D=1|Y=1)}{p(D=0|Y=1)} = \frac{0.2225}{1-0.2225} = 0.28617.\]</span> Cuando tengo un positivo en la prueba: tener ese positivo en la prueba diagnóstica aumenta la credebilidade de que tengo la enfermedad.</p>
<p><strong>Aumenta la credebilidad</strong> de tener la enfermedad, <strong>no la probabilidad</strong>. Ha aumentado en casi 28.83 %.</p>
<p><span class="math display">\[\text{Odd post-test (para un resultado positivo)} = \text{Odd pre-test} · DLR^+ = 0.0101 · 28.33 = 0.28613\]</span></p>
<p>Si pensamos en los resultados negativos:</p>
<ul>
<li><p>Partimos igual (sin hacerme la pruebea): 1 a favor de tenerlo vs 99 a favor de no tenerlo (el odd pre-test).</p></li>
<li><p>Al tener un resultado negativo: <span class="math inline">\(\text{Odd post-test (para un resultado negativo)} = \frac{p(D=1|Y=0)}{p(D=0|Y=0)} = \frac{1-0.9984}{0.9984} = \frac{1}{629} = 0.0016.\)</span> Pasamos de una credebilidad de tener 1 a 99 a una credebilidad de 1 de tener la enfermedad a 629 de no tenerla.</p></li>
</ul>
<p>¿Un resultado negativo es seis veces más verosimil en un paciente sano que en uno enfermo?</p>
<p>La <span class="math inline">\(DLR^−\)</span> mide cuántas veces más probable es obtener un resultado negativo en personas sin la enfermedad comparado con personas con la enfermedad.</p>
<p>Como <span class="math inline">\(DLR^− = 0.157 \approx \frac{1}{6}\)</span>, entonces sí. Un resultado negativo es aproximadamente 6 veces más probable en personas sanas que en personas con la enfermedad.</p>
</section><section id="diferencias-entre-valores-predictivos-y-dlr" class="level2"><h2 class="anchored" data-anchor-id="diferencias-entre-valores-predictivos-y-dlr">Diferencias entre valores predictivos y DLR</h2>
<p>[Under review]</p>
<table class="table">
<colgroup>
<col style="width: 13%">
<col style="width: 42%">
<col style="width: 44%">
</colgroup>
<thead><tr class="header">
<th><strong>Aspecto</strong></th>
<th><strong>Valores Predictivos (VPP, VPN)</strong></th>
<th><strong>Razones de Verosimilitud (DLR+ y DLR-)</strong></th>
</tr></thead>
<tbody>
<tr class="odd">
<td><strong>Definición</strong></td>
<td>Probabilidad de que un resultado positivo o negativo en una prueba corresponda con la presencia o ausencia real de la enfermedad.</td>
<td>Indican cuánto cambia la probabilidad de la enfermedad tras un resultado positivo (DLR+) o negativo (DLR-) en la prueba.</td>
</tr>
<tr class="even">
<td><strong>Dependencia del contexto</strong></td>
<td>Dependen de la prevalencia de la enfermedad en la población estudiada.</td>
<td>Independientes de la prevalencia de la enfermedad, ya que se basan solo en la sensibilidad y especificidad de la prueba.</td>
</tr>
<tr class="odd">
<td><strong>Interpretación</strong></td>
<td>Proporcionan información sobre la probabilidad posterior a partir de un resultado positivo o negativo.</td>
<td>Ayudan a actualizar las probabilidades pretest para obtener las probabilidades postest mediante el teorema de Bayes.</td>
</tr>
<tr class="even">
<td><strong>Utilidad clínica</strong></td>
<td>Son útiles para estimar directamente la probabilidad de enfermedad en un paciente individual.</td>
<td>Son útiles para ajustar probabilidades pretest y evaluar el impacto de un resultado de la prueba en el diagnóstico.</td>
</tr>
<tr class="odd">
<td><strong>Ventajas</strong></td>
<td>Fáciles de interpretar en términos de probabilidad para el médico o paciente.</td>
<td>No se ven afectados por la prevalencia, lo que los hace más estables en diferentes poblaciones.</td>
</tr>
<tr class="even">
<td><strong>Limitaciones</strong></td>
<td>Cambian según la prevalencia, lo que puede limitar su generalización a otras poblaciones.</td>
<td>Necesitan ser combinados con una probabilidad pretest para calcular una probabilidad postest interpretable.</td>
</tr>
<tr class="odd">
<td><strong>Ejemplo clínico (VPP, VPN)</strong></td>
<td>“Con un VPP de 90%, el paciente con un resultado positivo tiene un 90% de probabilidad de tener la enfermedad.”</td>
<td>“Con un DLR+ de 10, un resultado positivo multiplica por 10 las probabilidades pretest de que el paciente tenga la enfermedad.”</td>
</tr>
<tr class="even">
<td><strong>Ejemplo clínico (DLR+ y DLR-)</strong></td>
<td>“Con un VPN de 95%, un resultado negativo implica un 95% de probabilidad de no tener la enfermedad.”</td>
<td>“Con un DLR- de 0.1, un resultado negativo reduce significativamente la probabilidad de enfermedad.”</td>
</tr>
</tbody>
</table>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation column-body"><div class="nav-page nav-page-previous">
      <a href="../tema_02/tema_02.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">TEMA 2</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../tema_02/tema_02_2_comparacion_test_y_tamanyos_muestrales_I.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-title">2. Comparación de test y tratamiento del tamaño muestral (I) <span style="color:green;">✓</span></span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>